version: 3

silent: true

includes:
  regclient:
    taskfile: ./regclient
    dir: ./regclient

vars:
  IMAGE_REGISTRY: "cr.yandex/crp0gerlvm29cl3507qk"
  NENV: "node_modules"

tasks:
  _prettier:
    internal: true
    cmds:
      - "{{.NENV}}/.bin/prettier {{.COMMAND}}"

  _with_nvm:
    internal: true
    cmds:
      - "source ${HOME}/.nvm/nvm.sh && nvm use && {{.COMMAND}}"

  init:
    desc: Initialize project environment
    cmds:
      - echo 'Installing node version...'
      - task: _with_nvm
        vars: { COMMAND: "nvm install" }

      - echo 'Installing node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm clean-install" }

      - echo 'Installing husky pre-commit...'
      - task: _with_nvm
        vars: { COMMAND: "npm run prepare-husky" }

  lint:
    desc: Lint project
    cmds:
      - echo 'Running prettier checks...'
      - task: _prettier
        vars: { COMMAND: "--check ." }

  lint-fix:
    desc: Lint fix project
    cmds:
      - echo 'Running prettier fixes...'
      - task: _prettier
        vars: { COMMAND: "--write ." }

  clean:
    desc: Clean project environment
    cmds:
      - echo 'Cleaning node dependencies...'
      - rm -rf {{.NENV}}

  dependencies-update:
    desc: Update dependencies
    cmds:
      - echo 'Updating node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm update" }
      - task: _with_nvm
        vars: { COMMAND: "npm outdated" }
      - task: _with_nvm
        vars: { COMMAND: "npm audit" }

  # CI-specific

  ci-init:
    desc: Initialize project environment in CI
    cmds:
      - echo 'Installing node dependencies...'
      - npm clean-install

  ci-login-ghcr:
    desc: Login to GitHub Container Registry in CI
    requires:
      env:
        - GITHUB_TOKEN
    cmds:
      - echo 'Logging to GitHub Container Registry...'
      - echo "${GITHUB_TOKEN}" | docker login ghcr.io -u USERNAME --password-stdin
