name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint-pr:
    name: Lint PR
    runs-on: ubuntu-20.04

    permissions:
      contents: read

    container:
      image: ghcr.io/${{ github.repository_owner }}/ubuntu-ci:jammy-0.3.3
      credentials:
        username: ${{ secrets.ROBOT_GITHUB_USER }}
        password: ${{ secrets.ROBOT_GITHUB_READ_PACKAGES_TOKEN }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          task ci-init

      - name: Lint PR
        run: |
          task lint

      - name: Login to Github Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_READ_PACKAGES_TOKEN }}
        run: |
          task ci-login-ghcr

      - name: Check immutable tags
        run: |
          task regclient:immutable-check
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_READ_PACKAGES_TOKEN }}

      - name: Check mutable tags
        run: |
          task regclient:mutable-check
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_READ_PACKAGES_TOKEN }}
